### ISSUE TITLE
This should be a plugin for youtube-dl

### ISSUE THREAD

**Issue by kissgyorgy** [rharkanson/pyriscope#1]
Enough said. :smile: 
https://github.com/rg3/youtube-dl/tree/master/youtube_dl/extractor

**Comment by rharkanson** [comment]
Hey! Thanks for showing me that, I've actually never heard of youtube-dl until now and it looks amazing! It seems they already have a Periscope extractor in their list of extractors. And by eyeballing the code, it looks like each extractor is written to a specification used by the core program, so it is doubtful that they would need Pyriscope's code, but they are certainly free to fork the Pyriscope repo or borrow from its source. 😄
