### ISSUE TITLE
Error when live stream ends

### ISSUE THREAD

**Issue by chrisbog94** [rharkanson/pyriscope#13]
"UnboundLocalError: local variable 'pool' referenced before assignment"

Here is the full output:
`[Sat Aug 20 18:37:13.786452 2016] [:error] [pid 27632] Traceback (most recent call last):
[Sat Aug 20 18:37:13.786462 2016] [:error] [pid 27632]   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
[Sat Aug 20 18:37:13.786469 2016] [:error] [pid 27632]     self.run()
[Sat Aug 20 18:37:13.786476 2016] [:error] [pid 27632]   File "/usr/lib/python2.7/threading.py", line 763, in run
[Sat Aug 20 18:37:13.786483 2016] [:error] [pid 27632]     self.__target(*self.__args, **self.__kwargs)
[Sat Aug 20 18:37:13.786490 2016] [:error] [pid 27632]   File "/home/user/public_html/app/pyriscope.py", line 446, in process
[Sat Aug 20 18:37:13.786497 2016] [:error] [pid 27632]     if pool.is_complete() and os.path.exists(file_path):
[Sat Aug 20 18:37:13.786504 2016] [:error] [pid 27632] UnboundLocalError: local variable 'pool' referenced before assignment
[Sat Aug 20 18:37:13.786511 2016] [:error] [pid 27632]`

**Comment by rharkanson** [comment]
Just curious, are you running with Python 3? By the looks of the stack trace, it looks like it is using Python 2.7. Pyriscope is written for Python 3+ so no promises are made for previous versions. 

Line 446 does not contain the code in question, that is from line 505. Have you modified the script? 

If you are running the latest version of Pyriscope in Python 3, this shouldn't be an issue. The variable `pool` is used before the line in question, so nothing else is coming to mind at the moment.

**Comment by chrisbog94** [comment]
This can be closed. Another student that was using the code fucked it up himself. He edited the original code and broke stuff.

Sorry for the inconvenience!

**Comment by rharkanson** [comment]
No problem! Thank you for the quick response!
