### ISSUE TITLE
Latest Version - Still seems not to work

### ISSUE THREAD

**Issue by AlbertOneStone** [rharkanson/pyriscope#16]
Ok, live capture works. Replay seems not to work. Every Replay Download there is just an empty folder created.

using Last Version (09.12.) and Python 3.5.2

`Downloading broadcast information.
Downloading replay information. 
Downloading chunk list. 
Dowloading replay XXXXX.ts`

gets only an empty folder.

Update:
Still getting this Failure:
`Downloading broadcast information.
Downloading replay information.
Traceback (most recent call last): File "runpy.py", line 184, in _run_module_as_main
 "__main__", mod_spec)
  File "runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\pyriscope.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\pyriscope\__main__.py", line 23, in main
    processor.process(args)
  File "c:\python35\lib\site-packages\pyriscope\processor.py", line 456, in process
    access_public['cookies'][2]['Name'],
IndexError: list index out of range`

**Comment by zendesk-thittesdorf** [comment]
Looks like they made some more changes... Here's an update.
[processor.py.zip](https://github.com/rharkanson/pyriscope/files/643414/processor.py.zip)

**Comment by thittesdorf** [comment]
And they mucked again...
[processor.py.zip](https://github.com/rharkanson/pyriscope/files/643604/processor.py.zip)

**Comment by zendesk-thittesdorf** [comment]
[processor.py.zip](https://github.com/rharkanson/pyriscope/files/643606/processor.py.zip)

**Comment by AlbertOneStone** [comment]
Thank you. It still seems not to work. Same Failure.

**Comment by zendesk-thittesdorf** [comment]
For me, it will only work on urls that look like

> https://www.periscope.tv/w/2kk3kjwk3k3k

If it has the username in the url, it won't find the downloads  i.e.

> https://www.periscope.tv/username/2kk3kjwk3k3k

**Comment by Vol-2016** [comment]
Hi, zendesk-thittesdorf.

Please check your fix for this REPLAY:

https://www.periscope.tv/w/1gqGvRlpbeOGB 
https://www.periscope.tv/joe/1gqGvRlpbeOGB

I get here "No files to download", though these files exist, of course.

**Comment by zendesk-thittesdorf** [comment]
Both links work for me.  I would guess that the installed app isn't patching properly.  You can replace the script directly by putting it in the site-packages folder which for me is /usr/local/lib/python3.5/site-packages/pyriscope

**Comment by Vol-2016** [comment]
You're absolutely right, it solved the problem, thanks!

And btw - what about adapt your patch to kindred batch script by n3tman (https://github.com/n3tman/periscope.tv) ?

**Comment by Masclaux** [comment]
HI i'm already send a patch to the batch version.

here the link https://github.com/nikisby/periscope.tv/pull/12/commits/96d2d4ed3d82a999e27c28c59518049c2e1e1d39

Sincerly

**Comment by rharkanson** [comment]
Thanks again @zendesk-thittesdorf ! Your changes have been added to the latest version.
