### ISSUE TITLE
New playlist chunk file naming

### ISSUE THREAD

**Issue by f0xd3v** [rharkanson/pyriscope#31]
This is a new (?) chunk naming : 

> #EXTM3U
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-TARGETDURATION:4
> #EXT-X-VERSION:6
> #EXT-X-INDEPENDENT-SEGMENTS
> #EXT-X-MEDIA-SEQUENCE:0
> #EXTINF:2.013,
> chunk_1495313911638140902_0.ts
> #EXTINF:2.015,
> chunk_1495313911640510249_1.ts
> #EXTINF:2.013,
> chunk_1495313911642093563_2.ts
> #EXTINF:2.828,
> chunk_1495313944771249193_3.ts

And the tool is saying there are no chunks available.

**Comment by moooby** [comment]
I have been able to fix the issue by changing the chunk pattern regular expression.

In **processor.py** go to line **471**:

`chunk_pattern = re.compile(r'chunk_\d+\.ts')`
and change it to:
`chunk_pattern = re.compile(r'chunk(?:_\d+)+\.ts')`

This new regular expression should match the older chunk naming style:

> chunk_123456789.ts

as well as the new chunk naming style:

> chunk_123456789_1.ts

You can check the updated regular expression here to test with any pattern:
[https://regex101.com/r/mNCepQ/1](https://regex101.com/r/mNCepQ/1)

**Comment by f0xd3v** [comment]
Hi mooby, thanks for your reply. I did almost the same in https://github.com/rharkanson/pyriscope/commit/ed205b3b6931bfec11dea31e0617af5406e1be3e

**Comment by solarplex** [comment]
Looks like downloading replay doesnt work
