### ISSUE TITLE
Threads not closing?

### ISSUE THREAD

**Issue by Seongun** [rharkanson/pyriscope#7]
Hi, thanks for the amazing tool.

I noticed that while downloading multiple videos, the threads don't close at the end of each video download, but rather stays open. This has caused the program to bust a couple times while trying to continually download new videos, as the maximum number of threads were exceeded. Is there anything that can be done about this?

**Comment by rharkanson** [comment]
In the last couple of months I have had a lot on my plate. If I get some more free time I will look into this. Thank you for pointing it out.

**Comment by harmandeep-singh** [comment]
Hi Russell,
Thank you for the great work , i noticed you fixed the problem replay url :+1: 
Thank you!

**Comment by rharkanson** [comment]
Thank crusherw for fixing the thread starvation issues. And hopefully Periscope won't change their API around too much. Previously I pyriscope was expecting a string of a certain length, hardcoded, but I worked around it with another regex.
