### ISSUE TITLE
Pyriscope stopped working for downloading replays

### ISSUE THREAD

**Issue by maltoma** [rharkanson/pyriscope#8]
I am experienced user with pyriscope. I use Linux Mint 17.3 Rosa. Pyriscope is working for recording live streams but stopped working for downloading replays. It was working before. I got this error last 2 days: "Unable to download chunk"

Normally i got this error when broadcaster deletes his own broadcast. But last 2 days, i noticed although broadcaster doesn't delete his own streams, i can't download replays. It shows broadcasters' username and broadcast's start time and .ts file name; then "Unable to download chunk"

I tried Scopedown that is a periscope downloader for Android, same time. It showed how many chunk files that the live show contains, in the beginning, then gave 403 error. But another periscope downloader for android was working. Then I saw an update for scopedown. I updated. Update note was "fixed 403 error". So scopedown started to work again. Why did i tell this? I think periscope changed its system. So pyriscope may need an update.

Am i the only one that get this error when downloading replays?

**Comment by rharkanson** [comment]
This issue has been fixed. You assumed correctly, Periscope changed internally but Pyriscope 1.2.7 can handle replay downloading now.
